server:
  port: 8000
spring:
  application:
    name: visual-studio-api
  datasource:
    url: jdbc:mysql://mysql8:3306/visual_studio_db
    #    url: jdbc:mysql://localhost:3307/visual_studio_db
    username: root
    password: sa
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
